language: go

go:
  - 1.12.x

go_import_path: github.com/k8snetworkplumbingwg/network-attachment-definition-client
install: true
script: 
  - hack/verify-codegen.sh
  - go test ./pkg/...
  - go build ./cmd/example/
